services:
  app:
    build:
      context: .
      target: production
    environment:
      PORT: ${PORT:-3000}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      SCAN_INTERVAL: ${SCAN_INTERVAL:-5}

  migrate:
    build:
      context: .
      target: migrator
